# config_gpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
   replicaCount: 1
   spec:
      containerSpec:
         imageUri: gcr.io/bachelor-dev-377908/sweeper
         args: ["-e", "dataset=membrane", "save_path=compare_results/membrane"]
