# config_gpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-32
   diskSpec:
      bootDiskSizeGb: 200
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/bachelor-dev-377908/run_compare
      env:
         - name: dataset
           value: "warwick"
         - name: save_path
           value: "compare_results/warwick"
