# config_gpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n2-highcpu-16
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/bachelor-dev-377908/run_compare
      env:
         - name: dataset
           value: "PhC-C2DH-U373"
         - name: save_path
           value: "compare_results/PhC-C2DH-U373"
