# config_gpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-standard-8
      acceleratorType: NVIDIA_TESLA_V100
      acceleratorCount: 1
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/bachelor-dev-377908/run_compare
      env:
         - name: dataset
           value: "PhC-C2DH-U373"
         - name: save_path
           value: "compare_results/PhC-C2DH-U373"
